// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("calendar.caldav.googleResync", 1698139858);
user_pref("calendar.list.sortOrder", "686bd641-a181-4734-8b4c-35bc09ee53e7");
user_pref("calendar.registry.686bd641-a181-4734-8b4c-35bc09ee53e7.calendar-main-default", true);
user_pref("calendar.registry.686bd641-a181-4734-8b4c-35bc09ee53e7.calendar-main-in-composite", true);
user_pref("calendar.registry.686bd641-a181-4734-8b4c-35bc09ee53e7.disabled", true);
user_pref("calendar.registry.686bd641-a181-4734-8b4c-35bc09ee53e7.name", "Мой календарь");
user_pref("calendar.registry.686bd641-a181-4734-8b4c-35bc09ee53e7.type", "storage");
user_pref("calendar.registry.686bd641-a181-4734-8b4c-35bc09ee53e7.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Moscow");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1698139860);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230928194049");
user_pref("extensions.lastAppVersion", "115.3.1");
user_pref("extensions.lastPlatformVersion", "115.3.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"fa381504-81e1-4860-b7b3-c468f5fc8802\",\"google@search.mozilla.org\":\"5579dd31-3e54-4dc2-9e2f-c46ec85ee586\",\"ddg@search.mozilla.org\":\"8b63a09c-d0f2-4e11-8c52-a7762c446a96\",\"amazondotcom@search.mozilla.org\":\"23c946f1-ec3d-47a7-b2e7-3e7bd90c1651\",\"priceru@search.mozilla.org\":\"6fb5a055-ba54-4334-83a6-52a676ea8998\",\"wikipedia@search.mozilla.org\":\"766fae22-2b16-43ea-b108-b663cb419791\",\"ozonru@search.mozilla.org\":\"69558483-93ea-4e53-bbfd-0c3555a130b0\",\"bing@search.mozilla.org\":\"407393f1-7846-427a-b565-e476abcb6572\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.3.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Важное");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Рабочее");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Личное");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "К исполнению");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Отложено");
user_pref("mailnews.tags.version", 2);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1698139854);
user_pref("toolkit.telemetry.cachedClientID", "05b84620-c7f2-4bfd-990a-e9dc8c25a660");
user_pref("toolkit.telemetry.previousBuildID", "20230928194049");
